<!--
    Task 1:
    Loop through the contents of the $nav array and create a simple nav object
    Using basic string manipulation, make the content of the A tags contain the
    value of each element in the $nav array and make the HREF attribute a URL
    slug of the that value, for example:

        <a href="/new-orders">New Orders</a>

    (The $nav array variable is already available in this space via the view.)
//-->
<?php
    /*function takes in a nav array as :    $nav = [New Orleans]
    and prints hyperlinks as: 
    <a href="/new-orders">New Orders</a>
    */
    function generateLinks($nav){
        for($i=0; $i<count($nav);$i++){
            $content = $nav[$i];                            //content in array to show
            $slug = strtolower($content);
            $slug = str_replace(" ", "-", $slug);   //replace space with '-' if any
            echo ("<a href=".$slug.">$content</a>");
            echo "<br>";
        }
    }
    generateLinks($nav);
?>